# TODO: Create a Dockerfile for the HA RAG system

# TODO: Use python:3.10-slim as base image

# TODO: Set /app as working directory

# TODO: Copy and install requirements

# TODO: Copy application code

# TODO: Set the entry point to run app.py
